#!/usr/bin/env python3
"""Generate macOS strings from the canonical Windows language table."""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parents[1]
source = (root / 'src/lang_strings.h').read_text().replace('\\\n', '')
source = re.sub(r'/\*.*?\*/|//[^\n]*', '', source, flags=re.S)
strings = {}
for match in re.finditer(r'X\((\w+),\s*((?:L"(?:\\.|[^"\\])*"\s*,?\s*)+)\)', source):
    columns = re.split(r'"\s*,\s*L"', match[2])
    values = []
    for column in columns:
        if not column.startswith('L"'): column = 'L"' + column
        if not column.rstrip().endswith('"'): column += '"'
        values.append(''.join(json.loads('"' + part + '"') for part in re.findall(r'L"((?:\\.|[^"\\])*)"', column)))
    if len(values) != 4: raise ValueError(match[1])
    strings[match[1]] = values
assert len(strings) == len(re.findall(r"X\(\w+,", source)) and len(strings['KEYS_BODY']) == 4
extras = {
'COUNT_COLORS': ['Count colours', '色数を集計', '统计颜色数', '統計色數'],
'Color count cancelled': ['Color count cancelled', '色数の集計を中止しました', '颜色统计已取消', '色數統計已取消'],
'Color count skipped: transparency exceeds memory limit': ['Color count skipped: transparency exceeds memory limit', '透明色が多いためメモリ上限で集計を中止', '透明颜色过多，达到内存上限停止统计', '透明色過多，達到記憶體上限停止統計'],
'EMPTY': ['Drop an image here or press ⌘O', '画像をドロップするか ⌘O で開く', '拖放图像或按 ⌘O 打开', '拖放影像或按 ⌘O 開啟'],
'FINDER': ['Show in Finder', 'Finderで表示', '在 Finder 中显示', '在 Finder 中顯示'],
'File': ['File', 'ファイル', '文件', '檔案'],
'Image': ['Image', '画像', '图像', '影像'],
'Name': ['Name', '名前', '名称', '名稱'],
'Folder': ['Folder', 'フォルダ', '文件夹', '資料夾'],
'Size': ['Size', 'サイズ', '大小', '大小'],
'Modified': ['Modified', '更新日時', '修改时间', '修改時間'],
'Format': ['Format', '形式', '格式', '格式'],
'Dimensions': ['Dimensions', '寸法', '尺寸', '尺寸'],
'Bit depth': ['Bit depth', 'ビット深度', '位深度', '位元深度'],
'Color space': ['Color space', '色空間', '色彩空间', '色彩空間'],
'Transparency': ['Transparency', '透明度', '透明度', '透明度'],
'Frames': ['Frames', 'コマ数', '帧数', '格數'],
'Duration': ['Duration', '再生時間', '时长', '播放時間'],
'Properties': ['Properties', 'プロパティ', '属性', '屬性'],
'Embedded text': ['Embedded text', '埋め込みテキスト', '嵌入文本', '嵌入文字'],
'Colors': ['Colors', '色数', '颜色数', '色數'],
'Counting…': ['Counting…', '集計中…', '正在统计…', '正在統計…'],
'Truncated': ['Truncated', '上限により省略', '已截断', '已截斷'],
'Error': ['Error', 'エラー', '错误', '錯誤'],
'None': ['None', 'なし', '无', '無'],
'Yes': ['Yes', 'あり', '是', '是'],
'No': ['No', 'なし', '否', '否'],
'Unknown': ['Unknown', '不明', '未知', '未知'],
'Metadata limited to the first 64 frames': ['Metadata limited to the first 64 frames', 'メタデータは先頭64コマまで', '元数据仅限前64帧', '中繼資料僅限前64格'],
'PNG embedded text skipped: file exceeds 64 MiB': ['PNG embedded text skipped: file exceeds 64 MiB', '64 MiBを超えるためPNGテキストの解析を省略', '文件超过64 MiB，跳过PNG文本解析', '檔案超過64 MiB，略過PNG文字解析'],
'Metadata report truncated at 256 KiB': ['Metadata report truncated at 256 KiB', 'メタデータは256 Ki文字までで省略', '元数据截断至256 Ki字符', '中繼資料截斷至256 Ki字元'],
'Color count skipped: image exceeds 16 megapixels': ['Color count skipped: image exceeds 16 megapixels', '1600万画素を超えるため色数の集計を省略', '图像超过1600万像素，跳过颜色统计', '影像超過1600萬像素，略過色數統計'],
'Metadata depth limit': ['Metadata depth limit', 'メタデータの階層上限', '元数据层级上限', '中繼資料層級上限'],
'Metadata array limit': ['Metadata array limit', 'メタデータの配列上限', '元数据数组上限', '中繼資料陣列上限'],
}
strings.update(extras)
output = '// Generated by tools/make_macos_strings.py; Windows strings remain canonical.\n'
output += 'let localizedStrings: [String: [String]] = [\n'
for key, values in strings.items():
    output += '    ' + json.dumps(key, ensure_ascii=False) + ': ' + json.dumps(values, ensure_ascii=False) + ',\n'
output += ']\n'
path = root / 'macos/Strings.swift'
if '--check' in __import__('sys').argv:
    assert path.read_text() == output, 'Run python3 tools/make_macos_strings.py'
else:
    path.write_text(output)
print(f'{len(strings)} strings, four languages')
